version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dataforge-postgres
    environment:
      POSTGRES_USER: dataforge
      POSTGRES_PASSWORD: dataforge
      POSTGRES_DB: dataforge_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dataforge-network

  mongo:
    image: mongo:6
    container_name: dataforge-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dataforge-network

  minio:
    image: minio/minio
    container_name: dataforge-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - dataforge-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: dataforge-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - dataforge-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: dataforge-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dataforge-network

  spark:
    image: docker-spark:latest
    container_name: dataforge-spark
    depends_on:
      - kafka
    networks:
      - dataforge-network
    command: tail -f /dev/null


networks:
  dataforge-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  minio_data: